version: '3'
services:
  db:
    image: mysql:8.0.11
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  web:
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "4000:4000"
    depends_on:
      - db
      
volumes:
  mysql:
    driver: local